# Generated by Django 5.1.8 on 2025-04-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativaprova',
            name='nota',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questao',
            name='provas',
            field=models.ManyToManyField(related_name='questoes', to='core.prova'),
        ),
    ]
