# Generated by Django 5.1.8 on 2025-04-13 16:21
import zoneinfo
from django.db import migrations


def create_daily_task(apps, schema_editor):
    try:
        CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
        PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    except LookupError:
        return

    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute='59',
        hour='23',
        day_of_week='*',
        day_of_month='*',
        month_of_year='*',
        timezone=zoneinfo.ZoneInfo('America/Recife')
    )
    PeriodicTask.objects.get_or_create(
        crontab=schedule,
        name="Corrigir Provas",
        task="provas.tasks.corrigir_provas",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tentativaprova_nota_alter_questao_provas'),
    ]

    operations = [
        migrations.RunPython(create_daily_task, reverse_code=migrations.RunPython.noop)
    ]
