# Generated by Django 5.1.8 on 2025-04-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250413_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Peso da questão'),
            preserve_default=False,
        ),
    ]
