# Generated by Django 5.1.8 on 2025-04-15 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_questao_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('date_changed', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('prova', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.prova')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('date_changed', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('posicao', models.PositiveIntegerField()),
                ('nota', models.PositiveIntegerField()),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ranking')),
                ('tentativa_prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tentativaprova')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['posicao'],
                'unique_together': {('ranking', 'posicao')},
            },
        ),
    ]
